services:
    avathar.rankpoststyling.listener:
        class: avathar\rankpoststyling\event\listener
        arguments:
            - '@cache'
            - '@config'
            - '@request'
            - '@template'
            - '@user'
        tags:
            - { name: event.listener }
